FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY PasswordCheckerBackend.csproj ./
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "PasswordCheckerBackend.dll"]
